name: Deploy-Application-to-intune
on:
  workflow_call:
    inputs:
      ticket:
        description: "RITM"
        required: true
        type: string
      appName:
        description: "Application name to deploy"
        required: true
        type: string
      appLogo:
        description: "Application Logo"
        required: false
        type: string
      groupId:
        description: "Azure AD Group ID (optional)"
        required: false
        type: string
      dependentApp:
          description: 'Dependent Application Name'
          required: false
          type: string
      publisher:
        description: "Manufacturer of Application"
        required: false
        default: "Maersk"
        type: string
      description:
        description: "App's Description"
        required: false
        default: "Deployed via GitHub Actions, As part of AppLifeCycle Automation Deployment of Winget Package only"
        type: string
      
  workflow_dispatch:
    inputs:
      appName:
        description: 'App Display Name'
        required: true
        default: 'My App 1.0'
      groupId:
        description: 'Azure AD Group ID (optional)'
        required: false

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  deploy:
    runs-on: windows-2025
    environment: AutomationTesting
    outputs:
      job_status: ${{ job.status }}
    steps:
    - uses: actions/checkout@v4

    - name: Test Federated login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        allow-no-subscriptions: true

    - name: Download .intunewin package
      env:
        APP_NAME: ${{ github.event.inputs.appName}}
      uses: actions/download-artifact@v4
      with:
        name: "${{ env.APP_NAME }}-package"
        path: ./package

    - name: Locate .intunewin file
      id: find_file
      shell: pwsh
      run: |
          $file = Get-ChildItem -Path "./package" -Filter "*.intunewin" -Recurse | Select-Object -First 1
          $logofile = Get-ChildItem -Path "./package" -Filter "app-logo*" -Recurse | Select-Object -First 1
          <# if (-not $file) {
                Write-Error "No .intunewin file found in ./package"
                exit 1
              }
                if (-not $logofile) {
                Write-Error "No specific logo image found"
                exit 0
              }
          #>
           Write-Host "Found package: $($file.FullName)"
           Write-Host "Found Logo file: $($logofile.FullName)"
          "package_path=$($file.FullName)" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          "logo_path=$($logofile.FullName)" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

    - name: Create Win32Lob App
      shell: powershell
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      env:
        APP_NAME: ${{ github.event.inputs.appName || 'Default App' }}
        GROUP_ID: ${{ github.event.inputs.groupId }}
        APP_LOGO: ${{ github.event.inputs.appLogo }}
        APP_PUBLISHER: ${{ inputs.publisher }}
        APP_DESCRIPTION: ${{ inputs.description }}
        APP_NOTES: |
          Package Type: Winget
          Version: Latest
          Deployer: Applifecycle Team (Automation)
      run: |
        Write-Host $env:GITHUB_OUTPUT

        $logopath= "${{ steps.find_file.outputs.logo_path }}"
        $DependentApp= "${{ inputs.dependentApp }}"
        $Params = @{
          IntuneWinPath   =   "${{ steps.find_file.outputs.package_path }}"
          AppName         =   $env:APP_NAME
          Publisher       =   $env:APP_PUBLISHER
          InstallCmd      =   "ServiceUI.exe -process:explorer.exe Deploy-Application.exe -DeploymentType Install"
          UninstallCmd    =   "ServiceUI.exe -process:explorer.exe Deploy-Application.exe -DeploymentType Uninstall"
          DetectionFile   =   "Deploy-Application.exe"
          DetectionPath   =   "%ProgramFiles%"
          AppLogo         =   $logopath
          DependentAppId  =   $DependentApp
          Description     =   $env:APP_DESCRIPTION
          Notes = $env:APP_NOTES
        }

        if ($env:GROUP_ID -and $env:GROUP_ID.Trim()) {
          $Params['GroupId'] = $env:GROUP_ID
        }

        Write-Host "Params:`n$($( $Params.GetEnumerator() | Sort-Object Key | ForEach-Object { "{0} = {1}" -f $_.Key, $_.Value } ) -join "`n")"

        $scriptPath = Join-Path $env:GITHUB_WORKSPACE "automation-seed\workflow-scripts\deploy\intune-deployment.ps1"

        & $scriptPath @Params

  
  notify:
    needs: deploy
    if: always()
    uses: ./.github/workflows/ServiceNowNotifier.yml
    with:
      ticket: ${{ github.event.inputs.ticket }}
      job_status: ${{ needs.deploy.outputs.job_status }}
      success_message: " ${{ github.event.inputs.appName }}  successfully deployed to intune."
      failure_message: "${{ github.event.inputs.appName }} deployment failed"
      state: "close"
    secrets: inherit

  Upload-Artifacts-Sharepoint:
     runs-on: windows-2025
     needs: deploy
     steps:  
      - name: Upload Artifacts to SharePoint
        shell: powershell
        run: |
          Write-Host "Artifacts Uploaded to SharePoint"
